[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
  path = "/blog/*"
  function = "og-tags"

[[edge_functions]]
  path = "/g/*"
  function = "og-tags"

[[edge_functions]]
  path = "/gallery/*"
  function = "og-tags"
